### PR TITLE
JBTM-3955 Support for viewing logs in an activemq journal based store

### PR DESCRIPTION
**Pull request by mmusgrov**
https://issues.redhat.com/browse/JBTM-3955

!JDK21 !JACOCO

This PR follows up on https://github.com/jbosstm/lra/pull/14 and adds support for browsing ActiveMQ Journal based logs.

The docs for the feature are to be covered by issue https://issues.redhat.com/browse/JBTM-3784

### CODE REVIEW

**Comment by mmusgrov** [comment]
@marcosgopen There is something wrong with our AS_BRANCH (Rebasing the wildfly upstream/main on top of the AS_BRANCH). I don't know what changes were made when Toms changes were reverted by https://github.com/jbosstm/jboss-as/pull/94 but that is probably the cause.

**Comment by marcosgopen** [comment]
> @marcosgopen There is something wrong with our AS_BRANCH (Rebasing the wildfly upstream/main on top of the AS_BRANCH). I don't know what changes were made when Toms changes were reverted by [jbosstm/jboss-as#94](https://github.com/jbosstm/jboss-as/pull/94) but that is probably the cause.

Thanks @mmusgrov , I'll have a look.

**Comment by marcosgopen** [comment]
@mmusgrov I have updated the jboss-as, now we should be able to test this PR. I am re-starting the job.

**Comment by marcosgopen** [comment]
> LRA profile tests failed (https://ci-jenkins-csb-narayana.apps.ocp-c1.prod.psi.redhat.com/job/btny-pulls-lra/PROFILE=LRA,jdk=openJDK21,label=jnlp-agent/89/): LRA Test failed with failures in arq profile

The failing tests are not related to this PR ( I am investigating about those) so I approve the PR. Thanks @mmusgrov

**Review by marcosgopen — APPROVED** [review]

**Pull request merged**
